apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldschool
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "0.2"
              memory: "256Mi"
