apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slamdev-dev
commonLabels:
  env: dev
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      kind: Ingress
      name: oldschool
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.oldschool.com
