spring:
  application:
    name: oldschool
  datasource:
    url: jdbc:postgresql://localhost:5432/oldschool
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
  main:
    banner-mode: off
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  session:
    timeout: 24h
    jdbc:
      initialize-schema: never
  zipkin:
    enabled: false
  sleuth:
    sampler:
      probability: 1
  cloud:
    discovery:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 1m
server:
  error:
    include-stacktrace: always
  shutdown: graceful
decorator:
  datasource:
    p6spy:
      enable-logging: false
management:
  server:
    port: 8081
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
oldschool:
  logs:
    appender: CONSOLE
    access:
      enabled: true
      config-file: logback-access.xml
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/oldschool
    username: postgres
    password: postgres
oldschool:
  logs:
    appender: JSON
    access:
      config-file: logback-access-json.xml
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/oldschool
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
server:
  error:
    include-stacktrace: never
oldschool:
  logs:
    appender: JSON
    access:
      config-file: logback-access-json.xml
