spring:
  application:
    name: oldschool
  datasource:
    url: jdbc:postgresql://localhost:5432/oldschool
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
  main:
    banner-mode: off
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  session:
    timeout: 24h
    jdbc:
      initialize-schema: never
server:
  error:
    include-stacktrace: always
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/oldschool
    username: postgres
    password: postgres
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/oldschool
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
server:
  error:
    include-stacktrace: never
