apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldschool-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
