apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slamdev-prod
commonLabels:
  env: prod
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: oldschool
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prod.oldschool.com
