apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldschool-backend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: slamdev/oldschool
          ports:
            - name: http
              containerPort: 8080
